# Generated by Django 5.0.1 on 2024-01-12 22:06

from django.db import migrations
from users.models import User
from os import path, listdir
import json

class Migration(migrations.Migration):

    def load_seeding_data(apps, schema_editor):

        seed_data_dir = "data"
        path_to_data_dir = path.join(path.dirname(__file__), seed_data_dir)

        for file_name in listdir(path_to_data_dir):
            #Asumo que todos los json en este directorio van a ser usuarios válidos
            if (file_name.endswith(".json")):
                with open(path.join(path_to_data_dir, file_name)) as file:
                    user = json.load(file)
                    user_id = user['user_id']
                    users_following = user['users_following']
                    
                    created_user = User.objects.create(user_id=user_id, users_following=users_following)
                    created_user.save()

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_seeding_data),
    ]
